### PR TITLE
[Pydantic III] Use list/dict annotations

### PR DESCRIPTION
**Pull request by bendichter**
As of Python 3.9, standard collections (list, tuple, dict) can be used in typehints instead of List, Tuple, and Dict.

### CODE REVIEW

**Comment by h-mayorquin** [comment]
This will have conflicts with #1017.
How do you guys want to handle @CodyCBakerPhD ?

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin I was planning on doing a PR just like this after #1017 to avoid exactly that

**Comment by bendichter** [comment]
yeah, it may have been a bit early. Let's close this and wait

**Comment by CodyCBakerPhD** [comment]
The damage isn't too awful

**Comment by bendichter** [comment]
I'm unable to officially review since I opened this PR, but this looks good to me. I'm happy to merge once the tests pass

**Review by CodyCBakerPhD — APPROVED** [review]

**Review by h-mayorquin — APPROVED** [review]

**Pull request merged**
