### PR TITLE
support Python 3.11

### LINKED ISSUE #192: [Feature]: support python 3.11
### What would you like to see added to NeuroConv?

Can we try this and see if it works as-is? Maybe we can have it as a test that is not required to pass?

### Is your feature request related to a problem?

_No response_

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

fix #192

## Checklist

- [ ] Have you thoroughly read our [Developer Guide](https://neuroconv.readthedocs.io/en/main/developer_guide.html)?
- [ ] Have you ensured the PR description clearly describes the problem and solutions?
- [ ] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/neuroconv/pulls) for the same change?
- [ ] If this PR fixes an issue, is the first line of the PR description `fix #XXX` where `XXX` is the issue number?
- [ ] Did you update the [CHANGLOG.md](https://github.com/catalystneuro/neuroconv/blob/main/CHANGELOG.md) file on your branch to describe your changes?

### CODE REVIEW

**Comment by bendichter** [comment]
@CodyCBakerPhD I feel like these changes should trigger tests

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
OK fixed the CI here to both trigger and run the 3.11 addition (one of the benefits of using reusable workflows - otherwise it has to be on `main` to adjust such conditions)

**Comment by CodyCBakerPhD** [comment]
Something seems to be off with `h5py` installation with Python 3.11 - does PyNWB test against 3.11? If so how do they fix it?

**Comment by bendichter** [comment]
It looks like pynwb does not test against 3.11 yet

https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/workflows/run_all_tests.yml#L24

I'll check if 3.11 is supported by h5py

**Comment by CodyCBakerPhD** [comment]
Well, progress has been made at least.

Past the barrier of no `h5py`/`hdmf` 3.11 compatability

Now the hang-up is DLC2NWB and its continued reliance on tensorflow (which is not available for 3.11): I'll push a bit harder on that https://github.com/DeepLabCut/DeepLabCut/issues/2104, if we can at least get a fresh release of that package we can remove the requirement here.

Alternative approach for this PR would be to restrict the usage of the DLC interface to Python < 3.11, kind of like how we limited the CED interface to Python > 3.7

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Installing only scikit-learn on top of minimal SI does not solve the issue; https://github.com/catalystneuro/neuroconv/pull/234/files#diff-425328748cadd3688bba00c04b360b1903b6adfbe8d9058747855224f0d40d2cR4 (used in recent retrigger)

Should I try including numba as well?

**Comment by alejoe91** [comment]
@CodyCBakerPhD indeed it should be `numba` causing the issue. I'll push a fix on SI to not make it fail (and just skipping the unavailable qm)

**Comment by alejoe91** [comment]
Here it is: https://github.com/SpikeInterface/spikeinterface/pull/1224

**Comment by CodyCBakerPhD** [comment]
@alejoe91 testing against your fix branch now, we'll see if that does it

**Comment by CodyCBakerPhD** [comment]
Update

All dependencies have, to the best of my knowledge, been resolved (at least as far as imports can fail due to modules missing, etc.)

Though it does, similar to #237, require dropping Python 3.7

Right now however, the 'full' (on data) tests fail on all platforms due to timing out. The tests that ought to run in less than 10 minutes on linux end up taking 3+ hours and GitHub kills it.

Will have to investigate manually where the source of this stalling is, since it never explicitly raises any errors.

**Comment by CodyCBakerPhD** [comment]
The leak appears to have magically fixed itself over time...

All tests passing now for 3.11: https://github.com/catalystneuro/neuroconv/actions/runs/4147286971/jobs/7173996923

**Review by CodyCBakerPhD — DISMISSED** [review]

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
