### PR TITLE
Add pydocstyle to pre-commit for consistent docstrings

### LINKED ISSUE #284: [Testing]: check docstrings for consistency
### What would you like to see added to NeuroConv?

Replaces the dynamic parsing proposal of #278

Add simple tests that check the docstring description of both upstream arguments that are copied and propagated as well as internal repeated arguments

very low priority, however

### Is your feature request related to a problem?

_No response_

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

### PR DESCRIPTION
**Pull request by pauladkisson**
Fixes #284 pt 1

### CODE REVIEW

**Comment by h-mayorquin** [comment]
Yes, let's open a PR for each of those items. 

Concerning this PR, it is time for me to take a look into that hook.

**Comment by pauladkisson** [comment]
Sorry, but what do you mean one `DXYZ` at a time?

**Comment by CodyCBakerPhD** [comment]
D102, D103, D401, etc.

**Comment by pauladkisson** [comment]
Actually, bc of the way `DXYZ`s are selected via convention=numpy, and with tools like [docformatter](https://github.com/PyCQA/docformatter), I think it will be easiest to just do this all at once.

**Pull request closed without merging**
