### PR TITLE
reorganized weeklies into dedicated workflow like dailies

### PR DESCRIPTION
**Pull request by pauladkisson**
Continuation of #1081 for weekly workflows.

### CODE REVIEW

**Comment by pauladkisson** [comment]
@CodyCBakerPhD, for my own understanding, what is the reason that `Build and Upload Docker Image of Rclone With Config to GHCR` only runs weekly while all the rest of the active workflows run daily?

**Comment by CodyCBakerPhD** [comment]
> for my own understanding, what is the reason that Build and Upload Docker Image of Rclone With Config to GHCR only runs weekly while all the rest of the active workflows run daily?

The base image for rclone is not assumed to update that regularly or that its updates are not that important

Could maybe even go down to monthly

Main edge case benefit is that you gain access to new service providers (but most of our expected usage is drive/dropbox anyway)

**Comment by pauladkisson** [comment]
> The base image for rclone is not assumed to update that regularly or that its updates are not that important

Ok, sounds good.

**Review by h-mayorquin — COMMENTED** [review]
Should we put the formatwise gallyer tests here as well?

https://github.com/catalystneuro/neuroconv/blob/fddd4d28cb7839920479d8154f49417f78a391af/.github/workflows/formatwise-installation-testing.yml#L1-L73

Also, maybe the dev tests? They are on the dailies but we won't be able to fix them on a daily basis so once you get the notification once you will keep getting the notification every day. I guess that's your call.

**Comment by pauladkisson** [comment]
> Should we put the formatwise gallyer tests here as well?

Those are disabled, so I didn't include them.

**Comment by pauladkisson** [comment]
> Also, maybe the dev tests?

No, I definitely want to know about the dev tests on a daily basis.

**Comment by h-mayorquin** [comment]
> > Should we put the formatwise gallyer tests here as well?
> 
> Those are disabled, so I didn't include them.

OK, I think we should activate them. But that's outside of the scope of this PR.

**Review by h-mayorquin — APPROVED** [review]

**Pull request merged**
