### PR TITLE
rmv author docstrings from all modules

### PR DESCRIPTION
**Pull request by bendichter**
I'd like to remove author docstrings from modules. 

First, a much more detailed summary of contributions can be achieved through Git Blame, which can be accessed conveniently using the GitHub interface. This feature details the author, commit, and time of each line of code.

Second, I don't like the way these comments render in the API docs.

I think the main downside of this would be personal. I don't want anyone to think I am erasing the records of their contributions, I just think this is a sub-optimal way to record and communicate authorship.

### CODE REVIEW

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
> I think the main downside of this would be personal. I don't want anyone to think I am erasing the records of their contributions, I just think this is a sub-optimal way to record and communicate authorship.

Yeah, the GitHub [contributors](https://github.com/catalystneuro/neuroconv/graphs/contributors) + Blame is much more effective way to view that info

**Comment by bendichter** [comment]
@weiglszonja , @luiztauffer , @h-mayorquin , are you all OK with this?

**Comment by luiztauffer** [comment]
I'm fine with removing it

**Comment by h-mayorquin** [comment]
Yes. No problem on my side.

**Comment by bendichter** [comment]
This needs official approval from someone to go through

**Review by h-mayorquin — APPROVED** [review]
@weiglszonja ?

**Pull request merged**
