### PR TITLE
Fix #593

### LINKED ISSUE #593: [Bug]: Can't specify experiment type when converting .abf to .nwb with Neuroconv
### What happened?

I am trying to convert ABF files to NWB using the code from the Neuroconv Examples Gallery. 

When I execute interface.run_conversion(....), I get an error in the subroutine neo.py that the variable 'icephys_experiment_type' is returning the value None (see traceback below). 

I have tried inputing 'voltage_clamp', 'current_clamp', 'izero', and "" for this variable when I instantiate the metadata, but get the same error for all starting inputs. 

### Steps to Reproduce

```python
from neuroconv.datainterfaces import AbfInterface
# Metadata info
icephys_metadata = {

    "cell_id": "Cell3",

    "slice_id": "5C",

    "targeted_layer": "Superficial_CR",

    "inferred_layer": "",

    "recording_sessions": [

        {

            "abf_file_name": "test.abf",

            "stimulus_type": "long_square",

            "icephys_experiment_type": "voltage_clamp"

        }

    ]

}


# Instantiate data interface
interface = AbfInterface(

    file_paths=[r'C:\Users\Elizabeth\Desktop\Test\2023_09_18_0015.abf'],

    icephys_metadata=icephys_metadata

)

# Get metadata from source data and modify any values you want
metadata = interface.get_metadata()

metadata['NWBFile'].update(

    identifier="ID1234",

    session_description="Intracellular electrophysiology experiment.",

    lab="Southwell",                       # <-- optional

    institution="Duke University",             # <-- optional

    #experimenter=["EAM", "MA"],   # <-- optional

)

metadata["Subject"] = dict(

    subject_id="TE41",

    species="Homo sapiens",

    sex="M",

    date_of_birth="2022-03-15T00:00:00"

)

# Run conversion
output_folder = r'C:\Users\Elizabeth\Desktop\Test\single_abf_Conversion.nwb'
output_file = r'single_abf_Conversion.nwb'

interface.run_conversion(nwbfile_path=output_folder, metadata=metadata, overwrite=True)
```

### Traceback

```python
Traceback (most recent call last):

  Cell In[2], line 80
    interface.run_conversion(nwbfile_path=output_folder, metadata=metadata, overwrite=True)

  File ~\anaconda3\Lib\site-packages\neuroconv\basedatainterface.py:99 in run_conversion
    self.add_to_nwbfile(nwbfile_out, metadata=metadata, **conversion_options)

  File ~\anaconda3\Lib\site-packages\neuroconv\datainterfaces\icephys\baseicephysinterface.py:118 in add_to_nwbfile
    add_neo_to_nwb(

  File ~\anaconda3\Lib\site-packages\neuroconv\tools\neo\neo.py:414 in add_neo_to_nwb
    add_icephys_recordings(

  File ~\anaconda3\Lib\site-packages\neuroconv\tools\neo\neo.py:258 in add_icephys_recordings
    assert icephys_experiment_type in ["voltage_clamp", "current_clamp", "izero"], (

AssertionError: 'icephys_experiment_type' should be 'voltage_clamp', 'current_clamp' or 'izero', but received value None
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.9

### Package Versions

Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

### PR DESCRIPTION
**Pull request by luiztauffer**
Fix #593

### CODE REVIEW

**Comment by luiztauffer** [comment]
@CodyCBakerPhD this fix basically just guarantees that the match the extra info with the neo auto-extracted metadata, which is done by comparing the file names, works in more general cases... I believe in the tests we had one of the cases for which this was working already, but now is more general

**Comment by CodyCBakerPhD** [comment]
@luiztauffer If you know what the source issue is then, is it possible to add a test for it to ensure this doesn't re-occur? And also, do you think this could be a problem for any other interface?

**Comment by luiztauffer** [comment]
@CodyCBakerPhD I'm having problems running tests for gin data locally, due to:

```
test_gin_icephys.py:11: in <module>
    from neuroconv import NWBConverter
../../src/neuroconv/__init__.py:1: in <module>
    from .basedatainterface import BaseDataInterface
../../src/neuroconv/basedatainterface.py:9: in <module>
    from .tools.nwb_helpers import make_nwbfile_from_metadata, make_or_load_nwbfile
../../src/neuroconv/tools/__init__.py:2: in <module>
    from .nwb_helpers import get_module
../../src/neuroconv/tools/nwb_helpers/__init__.py:8: in <module>
    from ._models._base_dataset_models import DatasetConfiguration, DatasetInfo
../../src/neuroconv/tools/nwb_helpers/_models/_base_dataset_models.py:64: in <module>
    class DatasetConfiguration(BaseModel, ABC):
../../src/neuroconv/tools/nwb_helpers/_models/_base_dataset_models.py:131: in DatasetConfiguration
    @root_validator
/home/luiz/anaconda3/envs/nelson_lab_to_nwb_env/lib/python3.12/site-packages/pydantic/deprecated/class_validators.py:243: in root_validator
    return root_validator()(*__args)  # type: ignore
/home/luiz/anaconda3/envs/nelson_lab_to_nwb_env/lib/python3.12/site-packages/pydantic/deprecated/class_validators.py:249: in root_validator
    raise PydanticUserError(
E   pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```

Looks like pydantic v1 dependency problem remains here... I don't understand how the tests are running successfully on actions

**Comment by CodyCBakerPhD** [comment]
Using a fresh/new/up-to-date environment?

**Comment by luiztauffer** [comment]
neuroconv==this branch
pydantic==2.7.0

@root_validator has been deprecated

**Comment by CodyCBakerPhD** [comment]
Thanks for the test @luiztauffer

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
