### PR TITLE
Avoid modifying metadata in-place in the `VideoInterface` and `AbfInterface`

### PR DESCRIPTION
**Pull request by h-mayorquin**
This was discovered by @CodyCBakerPhD in #801

I am pushing her to get this fix to the main branch as quick as possible.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
What would you think about a test to add to the general mixin for ensuring metadata in equals metadata out after calling `add_to_nwbfile`?

**Comment by CodyCBakerPhD** [comment]
Also CHANGELOG

**Comment by h-mayorquin** [comment]
OK, I think even better. Let's start discussing how that would look like here:
https://github.com/catalystneuro/neuroconv/pull/815

Maybe it would be easier than what I think.

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by h-mayorquin** [comment]
Thanks for changing the title!

**Pull request merged**
