### PR TITLE
Adjust data install instructions

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Some feedback on confusion from @mavaylon1 (who is trying to set these up on HDMF for early warning of breakages)

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
(The files changed view doesn't show it great - the instructions for adjusting the config file and running the testing suite were buried in the 'update data' section, which is a separate topic)

**Review by h-mayorquin — APPROVED** [review]
OK.

**Comment by CodyCBakerPhD** [comment]
I believe these should work once `main` runs its daily tests in 30 minutes (and makes new caches with the new bumps for ephys)

**Comment by h-mayorquin** [comment]
> I believe these should work once `main` runs its daily tests in 30 minutes (and makes new caches with the new bumps for ephys)

I am confused by this, the PR looks like a change in documentation only. You mean you are changin something on the CI as well?

**Pull request merged**
