### PR TITLE
Path as string in FicTrac test

### PR DESCRIPTION
**Pull request by h-mayorquin**
Discussed in #804.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Any idea what's up with the commit history here?

**Comment by h-mayorquin** [comment]
No idea, do you want me to squash it?

**Comment by h-mayorquin** [comment]
No, I set it to the base PR here then it changed automatically when the other one was merged. Sure, I can do the other thing though.

**Comment by CodyCBakerPhD** [comment]
> No, I set it to the base PR here then it changed automatically when the other one was merged. Sure, I can do the other thing though.

I see, that would have the same effect due the upstream squash

**Pull request closed without merging**
