### PR TITLE
Brain wide map link

### PR DESCRIPTION
**Pull request by h-mayorquin**
This will send to the general page of the project. I don't know what the current link was supposed to do.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
It's supposed to lead to a file directory structure showing their source storage pattern

**Comment by CodyCBakerPhD** [comment]
Thank goodness we copied the directory structure explicitly into the example (minus the `...`) but IDK what good the generic link will do for helping explain the use case - maybe just no link at all then?

**Comment by CodyCBakerPhD** [comment]
Oh, IDK - the link still works for me: https://ibl.flatironinstitute.org/public/

**Comment by h-mayorquin** [comment]
It does work for me locally. Maybe it should go on the ignore list, most likely they blocked access to bots.

**Comment by CodyCBakerPhD** [comment]
The CI checker on other PRs has been flickering but not regularly failing - usually if I rerun it once it's fixed itself, so might just be slow server response times or something

**Comment by h-mayorquin** [comment]
All right, let's give it some time. I think that if it keeps being annoying for a month or so, then the link should get the honor of being in the ignored list.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin BTW the IBL link here has been stable for a while it seems so I think we can close

Problem lately has been SSL certificate of FicTrac: https://github.com/catalystneuro/neuroconv/actions/runs/8649412894/job/23715562511?pr=800#step:6:456

This is why I usually give it a week or more of consistent failures before even thinking about opening a PR to try to address them ourselves

**Comment by h-mayorquin** [comment]
OK, a week of consistent failure seems like a good criteria to open a PR. That's great. Let's close.

**Pull request closed without merging**
