### PR TITLE
Fix latest pynwb tests

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
These started failing on dev a few days ago, just now getting around to fixing them

### CODE REVIEW

**Review by h-mayorquin — APPROVED** [review]
OK. Is this because the timezone does not get added now? Is not returned?

**Comment by CodyCBakerPhD** [comment]
Timezone is no longer required or set automatically; I think it can also take `date` (not exact timestamp) now too

**Comment by h-mayorquin** [comment]
Thanks man! Maybe we should simplify the conversion gallery?

**Comment by CodyCBakerPhD** [comment]
I think the conversion gallery can still serve the purpose of _encouraging_ people to set exact times (with explicit, not assumed, timezones) as best practice

But I suppose a detail should be added somewhere about how if exact timestamps aren't known a basic date can suffice

**Comment by bendichter** [comment]
The thing is, that code is exactly the same for every interface, so maybe we could add a page to the conversion gallery that demonstrates how to create "DANDI-compatible NWB files"

**Comment by h-mayorquin** [comment]
I like that last idea. I also conceive the gallery as a minimal example "this is the fastest way of doing a conversion" so I want as little frictions as possible.

**Pull request merged**
