### PR TITLE
Fix make_or_load_nwbfile

### LINKED ISSUE #1114: [Bug]: Issue with DLC interface not loading
### What happened?

I am replicating the funny behavior I already described in #967: when running DLCInterface conversions, it fails silently not adding the correct fields in the nwb.

This time it was more painful as I forgot about the issue previously raised, and here it was 'in production'. I was running a batch conversion of multiple experiments:

```python
for exp in experiments:
    load_stuff()
    interfaces_pipe = make_interfaces()
    interfaces_pipe.run_conversion()
```

This resulted in *only the first experiment* missing all the DLC related stuff - which was driving me completely nuts for a good day of debugging, being those also quite slow operations, until I realized it sounded like the previous issue - and I fixed it adding a random 
```
from ndx_pose import PoseEstimation, PoseEstimationSeries
```

At the beginning of the script (alternatively, running twice the conversion of the first experiment :D)

This was massively annoying, I strongly suggest looking deeper into this or change the DLC example to document it.

This time it was happening from a different machine and different OS! (same interface though - always VSCode, running a script)

### Steps to Reproduce

The following code results in the bug:

```python
from datetime import datetime
from zoneinfo import ZoneInfo
from pathlib import Path
from neuroconv.datainterfaces import DeepLabCutInterface
import numpy as np

file_path = ".../....h5"
config_file_path = ".../config.yaml"
path_to_save_nwbfile = ".../test_nwb.nwb"

timestamps = np.array([1,2,3])  # stupid, speeds up processing if tstamps provided

interface = DeepLabCutInterface(file_path=file_path, config_file_path=config_file_path, 
                                subject_name="ind1", verbose=False)
interface.set_aligned_timestamps(timestamps)

metadata = interface.get_metadata()

session_start_time = datetime(2020, 1, 1, 12, 30, 0, tzinfo=ZoneInfo("US/Pacific"))
metadata["NWBFile"].update(session_start_time=session_start_time)

interface.run_conversion(nwbfile_path=path_to_save_nwbfile, metadata=metadata)

from pynwb import NWBHDF5IO

# confirm the file contains the new TimeSeries in acquisition
with NWBHDF5IO(path_to_save_nwbfile, "r") as io:
    read_nwbfile = io.read()
    print(read_nwbfile.processing)
```

The print states:
```
Fields:
  data_interfaces: {
    PoseEstimation <class 'pynwb.core.NWBDataInterface'>
  }
  description: processed behavioral data
}
```
And there is no data inside, unless I run the code twice or I add the initial import, in which case I get
```
Fields:
  data_interfaces: {
    PoseEstimation <class 'ndx_pose.pose.PoseEstimation'>
  }
  description: processed behavioral data
}
```
and data can be accessed.

### Traceback

_No response_

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.10

### Package Versions

`neuroconv == 0.6.4`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

### PR DESCRIPTION
**Pull request by pauladkisson**
This PR fixes a bug with `make_or_load_nwbfile` that pops up whenever extensions are lazily imported.

Fixes #1114 

See https://github.com/rly/ndx-pose/issues/36 for detailed example.

### CODE REVIEW

**Comment by pauladkisson** [comment]
@h-mayorquin, @rly,
 This fix works, but it rewrites any NWB files that are supposed to be appended, which could be slow for large NWB files.  I couldn't come up with anything better but interested to know what you both think.

**Comment by pauladkisson** [comment]
Ok, based on @rly's comments, I think we should wait on this until we have a function in pynwb that can update an io with the current global namespace. Then, we can keep append-mode support and just update the existing io.

**Comment by h-mayorquin** [comment]
@pauladkisson thanks for doing the detective work of tracking this bug and building an example. I tried this before and I failed.

This context manager has been a source of headaches and on top of that, I find it really difficult to read and understand. Cody and I wanted to break it into different pieces but never found the time and resources to do it.

If we could peel away the append mode functionality from the rest then we can create the io once all the calls to `add_to_nwbfile` are done and solve the problem for the 95 % of use cases.  We can then fix the append mode once the necessary machinery on pynwb is added. 

I think this is the way to move forward, let me know if there is something I am missing.

**Comment by rly** [comment]
> This context manager has been a source of headaches and on top of that, I find it really difficult to read and understand.

I agree. I know it is a Python feature, but I have never seen this syntax before and I find it unintuitive and confusing.

**Comment by pauladkisson** [comment]
> If we could peel away the append mode functionality from the rest then we can create the io once all the calls to add_to_nwbfile are done and solve the problem for the 95 % of use cases. We can then fix the append mode once the necessary machinery on pynwb is added.

Yeah, I think this is reasonable. What should we do with append in the mean time?

**Comment by h-mayorquin** [comment]
We can discuss a couple of general solutions but, as I mentioned in #1114  I think the necessary imports for `add_to_nwbfile` to work should be called at the `__init__` anyway. This will avoid this problem because all the uses of the context manager are inside `run_conversion` (which requires the interfaces to be already initialized and therefore the extension imports are already in place). Plus, I think it is good practice in general: Things should fail early if the extension library is missing in the executing environment.

**Pull request closed without merging**
