### PR TITLE
Get `session_start_time` from Neo reader for `OpenEphysLegacyRecordingInterface`

### PR DESCRIPTION
**Pull request by weiglszonja**
`OpenEphysLegacyRecordingInterface` doesn't need to rely on `pyopenephys` to get the start time of the recording.
This information is already in `self.recording_extractor.neo_reader` under `raw_annotations`.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
LGTM; the neo parser doesn't even use it either (https://github.com/NeuralEnsemble/python-neo/blob/2d63e18fb9a75131a2e54e32323cda23e2557356/neo/rawio/openephysrawio.py#L545)

Which makes me wonder, do we need the `pyopenephys` package at all then? Or can we remove it from the requirements for this interface?

**Comment by weiglszonja** [comment]
@CodyCBakerPhD I think the `OpenEphysBinaryRecordingInterface` would still need it because the [openephysbinaryrawio](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/openephysbinaryrawio.py) wouldn't have this "date_created" field like [here](https://github.com/NeuralEnsemble/python-neo/blob/2d63e18fb9a75131a2e54e32323cda23e2557356/neo/rawio/openephysrawio.py#L288).

**Comment by CodyCBakerPhD** [comment]
@weiglszonja Can you check if it has any equivalent in the neo annotations? If not then sure, I guess we have to keep it even just for the Binary version

**Comment by weiglszonja** [comment]
@CodyCBakerPhD I checked but didn't find it in the binary io reader.

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD I checked but didn't find it in the binary io reader.

@weiglszonja Thanks for checking!

**Pull request merged**
