### PR TITLE
in conversion yaml, data_interfaces must be a dictionary

### LINKED ISSUE #304: [Bug]: YAML data_interfaces should be a dict, not a list
### What happened?

Right now we in the conversion YAML format we have:

```yaml
data_interfaces:
  - SpikeGLXRecordingInterface
  - PhySortingInterface
```

but what if you want to include more than one SpikeGLXRecordingInterface? When specifying the inputs, how can you know which input is going to which interface? To solve this, we need to name the interfaces, similarly to how we specify the `NWBConverter` class. The names can be anything but must be unique amongst each other:

```yaml
data_interfaces:
  ap0: SpikeGLXRecordingInterface
  spike_sorting: PhySortingInterface
```

@CodyCBakerPhD, what do you think?

### Steps to Reproduce

```python
n.a.
```

### Traceback

_No response_

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.7

### Package Versions

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

### PR DESCRIPTION
**Pull request by bendichter**
in conversion yaml, data_interfaces must be a dictionary, not a list, and must be declared at the root level.

## Motivation
fix #304 

## Checklist

- [x] Have you thoroughly read our [Developer Guide](https://neuroconv.readthedocs.io/en/main/developer_guide.html)?
- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/neuroconv/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XXX` where `XXX` is the issue number?
- [x] Did you update the [CHANGLOG.md](https://github.com/catalystneuro/neuroconv/blob/main/CHANGELOG.md) file on your branch to describe your changes?

### CODE REVIEW

**Comment by bendichter** [comment]
> Is there a reason to forbid session or experiment-level definitions of 'extra' interfaces specific to those levels?

Only that it simplifies the yaml config files, the schema, and the conversion script without any loss of functionality. Is there a reason to keep them I'm not seeing?

**Comment by CodyCBakerPhD** [comment]
> Is there a reason to keep them I'm not seeing?

Not really, I just recall as a [design principle](https://github.com/catalystneuro/nwb-conversion-tools/pull/344#issue-1092200230) that the YAML script ought to handle global, experiment-level, and session-level `metadata` and `data_interfaces` (since each `data_interface` corresponds to a different sub-schema of `metadata`)

Happy to simplify it going forward if we wish to mimic Python top-level import approach (but I suspect `metadata` will have to still exist at each level)

**Comment by bendichter** [comment]
@CodyCBakerPhD in this case, I don't see any utility in specifying the data interfaces on the experiment or session level. You can infer whether we need it based on if there is source data for that interface label.

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
LGTM

**Pull request merged**
