### PR TITLE
[Bug] Fix stub times in recording interface

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@h-mayorquin Found this problem via the GUIDE

How would you like it to be tested?

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
(if not obvious from changelog; if you do any kind of alignment to the recording interface then try to run conversion in stub mode, you do not observe the alignment as being applied)

**Comment by CodyCBakerPhD** [comment]
cc @garrettmflynn

**Comment by h-mayorquin** [comment]
Is this a Spikeinterface problem? The times that were set are not propagated to `ConcatenateSegmentRecording`?

**Comment by CodyCBakerPhD** [comment]
> Is this a Spikeinterface problem? The times that were set are not propagated to ConcatenateSegmentRecording?

I wouldn't call it a 'bug' since it seems to be intended behavior (with both default `ignore_times=True` and `False`): https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/core/segmentutils.py#L125-L133

Now maybe it handles the segment t start or whatever it's called, but we're setting the actual timestamps of the vector as you can see

**Comment by CodyCBakerPhD** [comment]
Looks like there's already a test that maybe just needs fixing and a little enhancement?

https://github.com/catalystneuro/neuroconv/blob/fix_recording_interface_stub_times/tests/test_ecephys/test_ecephys_interfaces.py#L39-L42

**Comment by CodyCBakerPhD** [comment]
Any idea why `set_times` on the concatenated recording is complaining about the size mismatch? From the logic, they should be equivalent right?

**Comment by h-mayorquin** [comment]
> I wouldn't call it a 'bug' since it seems to be intended behavior (with both default ignore_times=True and False): https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/core/segmentutils.py#L125-L133

> Now maybe it handles the segment t start or whatever it's called, but we're setting the actual timestamps of the vector as you can see

Mmm I see.

> Any idea why `set_times` on the concatenated recording is complaining about the size mismatch? From the logic, they should be equivalent right?

Where? Or do you have a small script?

**Comment by h-mayorquin** [comment]
Ah, you mean on the testing -sorry-.

I will take a look at this!

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD I pushed a small fix. I does fix the problem but I am not sure if it will break something else. I think that my fix is the correct operation that should be carried out.

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD I pushed a small fix. I does fix the problem but I am not sure if it will break something else. I think that my fix is the correct operation that should be carried out.

Thank you 🙏

LGTM, pushing changelog then good to go

**Review by h-mayorquin — APPROVED** [review]

**Pull request merged**
