### PR TITLE
Try new badges

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
From Paul in #753

### CODE REVIEW

**Comment by pauladkisson** [comment]
Badge just says python: missing.

maybe adjust some setting in pypi?

**Comment by CodyCBakerPhD** [comment]
There's not many things customizable directly on PyPI - I believe it needs the classifiers in the setup when built, so this will show missing until next release, which I'll look into cutting tomorrow now that we have those bug fixes to configuration and buffering through

**Comment by h-mayorquin** [comment]
Cool!

**Review by pauladkisson — APPROVED** [review]

**Comment by h-mayorquin** [comment]
I guess we are only missing python 3.12 : )

**Pull request merged**
