### PR TITLE
Remove editable installs in the CI

### PR DESCRIPTION
**Pull request by h-mayorquin**
Trying to see if I can fix the need of editable installs for code coverage.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Only shows a single commit for this branch: https://github.com/catalystneuro/neuroconv/pull/756

Is there a logged run that shows a printout of the coverage report, confirming that it found lines and counted  hits?

**Comment by h-mayorquin** [comment]
> Only shows a single commit for this branch: #756
> 
> Is there a logged run that shows a printout of the coverage report, confirming that it found lines and counted hits?

It seems so:
https://app.codecov.io/github/catalystneuro/neuroconv/tree/ci_use_non_editable_actions

And this:
https://github.com/catalystneuro/neuroconv/actions/runs/8007324022/job/21871213241?pr=756

**Comment by CodyCBakerPhD** [comment]
> It seems so:

Link says 'No coverage reports found in this timespan.' (3 months)

> And this:

Can you link in that log the exact line of the printout of the coverage report? I see a SHA1 but no contents

**Comment by h-mayorquin** [comment]
> > It seems so:
> 
> Link says 'No coverage reports found in this timespan.' (3 months)

It does not for me. It shows 91.18 per cent.

> > And this:
> 
> Can you link in that log the exact line of the printout of the coverage report? I see a SHA1 but no contents

You can see the track of the last commit here:
https://app.codecov.io/github/catalystneuro/neuroconv/commit/cb79b6c10b3f54306ed0eedfa6961c5494aa9410/tree/src/neuroconv?displayType=list

**Comment by CodyCBakerPhD** [comment]
> It does not for me. It shows 91.18 per cent.

I see that now too, it looks like when I checked it was 4 minutes after the codecov bot posted, so probably it was still processing (that commit also didn't show up when I checked at that time)

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
