### PR TITLE
TDTFiberPhotometryInterface

### PR DESCRIPTION
**Pull request by pauladkisson**
This PR adds a DataInterface for TDT Fiber Photometry data.

### CODE REVIEW

**Comment by luiztauffer** [comment]
Wouldn't it be better to have different streams as different ResponseSeries? e.g., instead of this:
```yaml
FiberPhotometryResponseSeries:
  - name: fiber_photometry_response_series
    description: The fluorescence from the DMS calcium signal, DMS isosbestic control, DLS calcium signal, and DLS isosbestic control.
    stream_names: ["Dv2A", "Dv1A", "Dv4B", "Dv3B"]
    stream_indices: [null, null, null, null]
    unit: a.u.
    fiber_photometry_table_region: [0, 1, 2, 3]
    fiber_photometry_table_region_description: The region of the FiberPhotometryTable corresponding to the DMS calcium signal, DMS isosbestic control, DLS calcium signal, and DLS isosbestic control.
```

have this:

```yaml
FiberPhotometryResponseSeries:
  - name: dms_calcium_signal
    description: The fluorescence from the DMS calcium signal.
    stream_name: "Dv2A"
    stream_indice: 0
    unit: a.u.
    fiber_photometry_table_region: 0
    fiber_photometry_table_region_description: The region of the FiberPhotometryTable corresponding to the DMS calcium signal.
  - name: dms_isosbestic_control
    description: The fluorescence from the DMS calcium signal, DMS isosbestic control, DLS calcium signal, and DLS isosbestic control.
    stream_names: "Dv1A"
    stream_indices: 0
    unit: a.u.
    fiber_photometry_table_region: 1
    fiber_photometry_table_region_description: The region of the FiberPhotometryTable corresponding to the DMS isosbestic control.
```

@pauladkisson

**Comment by pauladkisson** [comment]
For the testing file, I have some code that stubbed it, but I'm not sure if that should be maintained somewhere or not. @CodyCBakerPhD, what is the best practice here?

**Comment by CodyCBakerPhD** [comment]
> For the testing file, I have some code that stubbed it, but I'm not sure if that should be maintained somewhere or not. @CodyCBakerPhD, what is the best practice here?

I would keep it documented somewhere somehow, perhaps as a gist or personal notes?

Jeremy Magland keeps all of his such stuff in a scratch realm

Julia Sprenger had similar helper functions stored somewhere adjacent to `neo` as I recall



> [pauladkisson](https://github.com/pauladkisson) requested a review from [CodyCBakerPhD](https://github.com/CodyCBakerPhD) [11 minutes ago](https://github.com/catalystneuro/neuroconv/pull/920#event-13782780571)

PR is still in draft state and at any rate I have been so displaced from fibre photometry I will let @luiztauffer and @alessandratrapani take charge reviewing this

**Review by alessandratrapani — APPROVED** [review]
Docs, metadata, and data interface look good, but since I never worked with tdt photometry data, I'll let @luiztauffer give the final approval.

**Review by luiztauffer — APPROVED** [review]

**Pull request merged**
