### PR TITLE
Use a github action to centralize gin data preparation

### PR DESCRIPTION
**Pull request by h-mayorquin**
While working on  #1013 I was having trouble getting the data right from the caches (see the diff in that PR). Centralizing the logic should make this kind of problem easier to deal with.

This is a partial move in the direction of #993.

### CODE REVIEW

**Review by pauladkisson — CHANGES_REQUESTED** [review]
Looks good, this PR should probably delete update-s3-testing-data.yml to avoid confusion.

**Comment by h-mayorquin** [comment]
> Looks good, this PR should probably delete update-s3-testing-data.yml to avoid confusion.

What possible confusion do you in mind?

**Comment by pauladkisson** [comment]
> > Looks good, this PR should probably delete update-s3-testing-data.yml to avoid confusion.
> 
> What possible confusion do you in mind?

update-s3-testing-data.yml is disabled, and actions/load-data seems to be a replacement (is it not?), so we should delete update-s3-testing-data.yml to avoid maintaining vestigial workflows that aren't in use.

**Comment by h-mayorquin** [comment]
> > > Looks good, this PR should probably delete update-s3-testing-data.yml to avoid confusion.
> > 
> > 
> > What possible confusion do you in mind?
> 
> update-s3-testing-data.yml is disabled, and actions/load-data seems to be a replacement (is it not?), so we should delete update-s3-testing-data.yml to avoid maintaining vestigial workflows that aren't in use.

No, it is not meant to replace it. This assumes the data is already on the s3 and loads it either from the cache or from the s3 if the former fails. At the moment we don't have a mechanism to automatically transfer the data from gin to s3. We should meet at brainstorm that.

**Comment by pauladkisson** [comment]
> No, it is not meant to replace it. This assumes the data is already on the s3 and loads it either from the cache or from the s3 if the former fails. 

I see. update-testing-data.yml on roiextractors is more like load-data/action.yml than update-s3-testing-data.yml, so that's why I misunderstood.

> At the moment we don't have a mechanism to automatically transfer the data from gin to s3. We should meet at brainstorm that.

gin is very finnicky, so we might just be better off keeping our current (manual) system.

**Review by pauladkisson — APPROVED** [review]

**Comment by pauladkisson** [comment]
> What troubles have you experienced?

Failed downloads mostly.

**Pull request merged**
