### PR TITLE
remove spikeextractors_backend options

### PR DESCRIPTION
**Pull request by bendichter**
## Checklist

- [ ] Have you thoroughly read our [Developer Guide](https://neuroconv.readthedocs.io/en/main/developer_guide.html)?
- [ ] Have you ensured the PR description clearly describes the problem and solutions?
- [ ] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/neuroconv/pulls) for the same change?
- [ ] If this PR fixes an issue, is the first line of the PR description `fix #XXX` where `XXX` is the issue number?
- [ ] Did you update the [CHANGLOG.md](https://github.com/catalystneuro/neuroconv/blob/main/CHANGELOG.md) file on your branch to describe your changes?

### CODE REVIEW

**Comment by bendichter** [comment]
@alejoe91 can you please help port https://github.com/catalystneuro/neuroconv/blob/main/tests/test_ecephys/test_tools_spikeextractors.py to use the new spikeinterface functions instead of spikeextractors?

**Comment by CodyCBakerPhD** [comment]
Is the plan to combine/merge this with #309 or do removals modularly?

> https://github.com/catalystneuro/neuroconv/blob/main/tests/test_ecephys/test_tools_spikeextractors.py 

Those changes in particular would be needed on #309, which removes the tools level support

**Comment by alejoe91** [comment]
> @alejoe91 can you please help port https://github.com/catalystneuro/neuroconv/blob/main/tests/test_ecephys/test_tools_spikeextractors.py to use the new spikeinterface functions instead of spikeextractors?

Shouldn't we just just remove the `test_tools_spikeextractors.py`? We already have the `test_tools_spikeinterface.py` which tests the same write functions with the new API

**Comment by bendichter** [comment]
duplicate of 309

**Pull request closed without merging**
