### PR TITLE
Add timestamps optimization warning in dlc

### PR DESCRIPTION
**Pull request by h-mayorquin**
Agreed follow up on https://github.com/catalystneuro/neuroconv/pull/967 

Check it out @vigji  

image

Note that a half an hour video took less than a minute in my computer. Your performance was way worse @vigji ?

### CODE REVIEW

**Comment by vigji** [comment]
Sorry, don’t have my computer and can’t these it this week, but from memory it was approx 5-10 mins to load 2 h movies at 100 Hz from an SSD using a MacBook Pro 2021

**Comment by h-mayorquin** [comment]
Ok, that makes sense, it is on the ballpark. I just wanted to know if performance was more variable than that.

What do you think of the warning message on the screenshot?

**Comment by vigji** [comment]
It looks reasonable to me! Would definitively address my concern.

**Comment by h-mayorquin** [comment]
Good, this is ready then @CodyCBakerPhD .

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
