### PR TITLE
[DO NOT MERGE]: Spell-checker

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Just curious if/how this works

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Spell checker can be a bit finnicky when it comes to all the weird data/code words and formats we use. Added a bunch of false positives to the exclusion file linked in the toml...

However, after all that it can be pretty useful. Found a lot of spelling errors everywhere - the output can be saved with `pylint --disable all --enable spelling --rcfile=pyproject.toml ./src  > ../test_results.txt` and appears much like NWB Inspector reports: [spelling_results.txt](https://github.com/catalystneuro/neuroconv/files/9229252/spelling_results.txt)

**Comment by CodyCBakerPhD** [comment]
Shows up the CI similarly: 
image

**Comment by CodyCBakerPhD** [comment]
Goal for this PR is to just let this sit on this side-branch and act as a stand-alone display whenever we want to scrub for spelling errors.

Will never require this for actual PRs.

**Review by h-mayorquin — CHANGES_REQUESTED** [review]
Holding this for the moment as discussed with @CodyCBakerPhD

**Comment by h-mayorquin** [comment]
Nice!

**Pull request closed without merging**
