### PR TITLE
 #688 roundtrip test with Spikeinterface

### PR DESCRIPTION
**Pull request by h-mayorquin**
Less confident as this one so opening it as a chained PR to the first one in #688. 

Tell me what you think @alejoe91 and @CodyCBakerPhD .

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Any idea what the current failures from this PR are about?

**Comment by h-mayorquin** [comment]
Windows can't erase folders or files that are still being used (linux does delaying magic under the hood so you can always call unlink). Something that I did over there leaves a reference open and windows is complaining. A recurring problem in spikeinterface.

**Comment by CodyCBakerPhD** [comment]
> Windows can't erase folders or files that are still being used (linux does delaying magic under the hood so you can always call unlink). Something that I did over there leaves a reference open and windows is complaining. A recurring problem in spikeinterface.

I mean the dev failures (which also seem to be present on `main`? https://github.com/catalystneuro/neuroconv/actions/runs/7250775580/job/19751708053)

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
Sorry, did not get you. There is a fix for the others tests here:

https://github.com/catalystneuro/neuroconv/pull/693

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
