### PR TITLE
Create aux method for choosing iterator type (for #90)

### PR DESCRIPTION
**Pull request by weiglszonja**
To be merged into #90

### CODE REVIEW

**Review by h-mayorquin — APPROVED** [review]
Looks good to me. I am curios about the default of `buffer_size=10` for the old data chunk iterator, isn't that useful for the new one as a default?

Also, not related to this but I am of the opinion that there is no reason to maintain the old functionality given that we have explicitly designed 'v2' to be better.

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
> Looks good to me. I am curios about the default of buffer_size=10 for the old data chunk iterator, isn't that useful for the new one as a default?

New defaults are better, keeping this one to maintain consistent behavior.


> Also, not related to this but I am of the opinion that there is no reason to maintain the old functionality given that we have explicitly designed 'v2' to be better.

The 'better' isn't quite as clear cut in this case - their behavior matches more closely than it did in the ecephys case and performance wasn't different by orders of magnitude. They do, however, work in markedly different ways and produce different behavior (`v1` keeps dimensions 'open' for example, which can be undesired in some circumstances but desired in others), and again they are powered by completely different code bases so if a bug appeared in `v2` there's a very good chance you could rollback and use `v1` safely.

**Comment by CodyCBakerPhD** [comment]
Thanks a bunch @weiglszonja

**Comment by h-mayorquin** [comment]
> > Looks good to me. I am curios about the default of buffer_size=10 for the old data chunk iterator, isn't that useful for the new one as a default?
> 
> New defaults are better, keeping this one to maintain consistent behavior.
> 
> > Also, not related to this but I am of the opinion that there is no reason to maintain the old functionality given that we have explicitly designed 'v2' to be better.
> 
> The 'better' isn't quite as clear cut in this case - their behavior matches more closely than it did in the ecephys case and performance wasn't different by orders of magnitude. They do, however, work in markedly different ways and produce different behavior (`v1` keeps dimensions 'open' for example, which can be undesired in some circumstances but desired in others), and again they are powered by completely different code bases so if a bug appeared in `v2` there's a very good chance you could rollback and use `v1` safely.

Thanks for explaining this one.

**Pull request merged**
