### PR TITLE
Update documentation dependencies

### PR DESCRIPTION
**Pull request by h-mayorquin**
While working on #45 I noticed that are behind in most of the dependencies. Testing if this can be updated.

### CODE REVIEW

**Comment by h-mayorquin** [comment]
I also realized that we are installing the `"sphinx_search.extension"` extension but we are not using it. I enabled it and it installs properly but it does not seem to work:

image

I am curios if it will work once merged. If it does not, I will disable it and then open an issue with it.

**Comment by CodyCBakerPhD** [comment]
Is the PR base for this correct?

**Comment by h-mayorquin** [comment]
> Is the PR base for this correct?

Apparently when you don't delete the merge branch the base is not changed automatically.

**Comment by CodyCBakerPhD** [comment]
> Apparently when you don't delete the merged branch the base is not changed automatically.

@h-mayorquin Gotcha - let me know if the sphinx-search works or not after merge

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by h-mayorquin** [comment]
> > Apparently when you don't delete the merged branch the base is not changed automatically.
> 
> @h-mayorquin Gotcha - let me know if the sphinx-search works or not after merge

@CodyCBakerPhD It am happy to say that it did. It is interesting that this did not work in the read the docs PR's built. Any idea on why that could be? I have to say it just was a wild guess on my side that it would.

**Comment by CodyCBakerPhD** [comment]
> > > Apparently when you don't delete the merged branch the base is not changed automatically.
> > 
> > 
> > @h-mayorquin Gotcha - let me know if the sphinx-search works or not after merge
> 
> @CodyCBakerPhD It am happy to say that it did. It is interesting that this did not work in the read the docs PR's built. Any idea on why that could be? I have to say it just was a wild guess on my side that it would.

No clue, never used this feature myself. In terms of the build workflow there’s virtually no difference from the PR builds and the main page

**Pull request merged**
