### PR TITLE
Remove upcoming deprecations

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
We were a bit delayed by the SpikeInterface release, but since we're changing the import structure anyway we might as well clean up other stuff ahead of the upcoming release.

The `icephys` module still has the `save_path` deprecation warning it since we caught that one much later than the others - should we remove it here as well?

### CODE REVIEW

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD I am curios how much the coverage will increase with this one.

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD I am curios how much the coverage will increase with this one.

Lol. We probably should have used `# pragma` on that originally.

**Comment by CodyCBakerPhD** [comment]
But it's meaningless coverage either way so it's just artificial inflation/deflation

**Comment by h-mayorquin** [comment]
> But it's meaningless coverage either way so it's just artificial inflation/deflation

Don't be a party popper, @CodyCBakerPhD  : P

**Comment by CodyCBakerPhD** [comment]
This branch got tangled with the ROI centroid stuff somehow. Re-doing

**Pull request closed without merging**
