### PR TITLE
Updated make_environment file to match tested python versions

### LINKED ISSUE #742: [Bug]: make_environment.yml leads to installation error
### What happened?

I created the `neuroconv_environment` via the `make_environment.yml` file and then installed neuroconv (full and test) and got an installation error.

Note the python version is 3.12.1 NOT 3.7 (there was no option on the dropdown)

### Steps to Reproduce

```python
conda env create -f make_environment.yml
conda activate neuroconv_environment
pip install -e .'[full,test]'
```

### Traceback

```python
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/opt/anaconda3/envs/neuroconv_environment/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/anaconda3/envs/neuroconv_environment/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/neuroconv_environment/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/neuroconv_environment/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/envs/neuroconv_environment/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/s3/qb42pmpn5jd0xb6fm2gt65qm0000gn/T/pip-build-env-tus00p4_/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/s3/qb42pmpn5jd0xb6fm2gt65qm0000gn/T/pip-build-env-tus00p4_/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/s3/qb42pmpn5jd0xb6fm2gt65qm0000gn/T/pip-build-env-tus00p4_/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.7

### Package Versions

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

### PR DESCRIPTION
**Pull request by pauladkisson**
Fixes #742 by specifying only the python versions that are actually tested (3.8-3.11).  Before, make_environment would use python 3.12 which led to a bug.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Do we actually even think there's a reason to use this file at all? Standard [dev mode installation](https://neuroconv.readthedocs.io/en/main/developer_guide/testing_suite.html#run-all-tests) instructions ought to be sufficient if we just place that part of the README

cc @bendichter @h-mayorquin

**Comment by h-mayorquin** [comment]
> Do we actually even think there's a reason to use this file at all? Standard [dev mode installation](https://neuroconv.readthedocs.io/en/main/developer_guide/testing_suite.html#run-all-tests) instructions ought to be sufficient if we just place that part of the README
> 
> cc @bendichter @h-mayorquin

Some people like conda and it does not cost a lot so far.

I am neutral about it.

**Comment by CodyCBakerPhD** [comment]
> Some people like conda 

Removing the file does not prevent people from using conda - also nothing significant changes between their conda environments using this method and the one we use all the time

The main advantage would be if we outright required specific versions of certain packages available only on conda-forge (like we do on the GUIDE), we could specify them here but not in the normal requirements file for `pip`

> it does not cost a lot so far.

The cost is one more file to have to maintain (which wasn't), documentation about how to use that file, as well as tests (which are completely missing) that ensure it works all the time. That cost is what triggered this issue/PR to begin with

**Comment by h-mayorquin** [comment]
> > Some people like conda
> 
> Removing the file does not prevent people from using conda - also nothing significant changes between their conda environments using this method and the one we use all the time

I mean creating environments with conda. That's what the file is for.

**Comment by CodyCBakerPhD** [comment]
> I mean creating environments with conda. That's what the file is for.

But you don't need the file to create a conda environment

What I mean is you can just make your own, call it anything you want, and specify the exact version of Python to use

```
conda create -n <name of environment> python=3.XY
conda activate <name of environment>
pip install -e .
```

If you mean that some people like to create their environments with less control using one fewer line via `conda env create -f <file path>` well then, yes - but I say the cost to reliably maintain that one feature is not worth it, considering this has been broken for a while now and would break again when we deprecate 3.8, and until we finish bumping to 3.12, etc.

**Comment by h-mayorquin** [comment]
> If you mean that some people like to create their environments with less control using one fewer line via conda env create -f <file path> well then, yes - but I say the cost to reliably maintain that one feature is not worth it, considering this has been broken for a while now and would break again when we deprecate 3.8, and until we finish bumping to 3.12, etc.

Yes, this is what I mean. Yeah, small gain but I also think that the maintenance burden is very low as well. I use to be an user of this feature but not anymore I guess that if @pauladkisson is fine with eliminating it that would make sense. I will trust your gut on this one.

**Comment by h-mayorquin** [comment]
Ah, I see you opened another PR already.

**Pull request closed without merging**
