### PR TITLE
Use mixing tests for mocks

### PR DESCRIPTION
**Pull request by h-mayorquin**
We have specific tests for the mock recording interface that duplicates the tests on the mixing. This PR solves this by using the mixing tests for the mock (We already doing that in the ophys side). 

This PR also separates some changes that I did on https://github.com/catalystneuro/neuroconv/pull/1124 and should come before it.

### CODE REVIEW

**Review by pauladkisson — CHANGES_REQUESTED** [review]
Looks good to me, but we should remove the 'old' Test classes before we merge right?

**Comment by h-mayorquin** [comment]
> Looks good to me, but we should remove the 'old' Test classes before we merge right?

I remove the ones from the Old Recording Extractor. I don't really like the stub tests were done in the old tests. Since those were written I have written better machinery on the SpikeInterface side. I will update those in a separate PR though and then remove the old ones.

**Comment by pauladkisson** [comment]
I see, so you'll remove those old tests after #1124 is ready to go?

**Comment by pauladkisson** [comment]
Also looks like test_no_slash_in_name is failing...

**Comment by h-mayorquin** [comment]
> I see, so you'll remove those old tests after #1124 is ready to go?

Yes, if not before.

**Comment by h-mayorquin** [comment]
> Also looks like test_no_slash_in_name is failing...

Should be fixed now.

**Comment by pauladkisson** [comment]
> > I see, so you'll remove those old tests after #1124 is ready to go?
> 
> Yes, if not before. I just don't want this to get in the way of #1124 as it would just be a cleaning/refactor PR and #1124 is building towards and enhancement coming from a user request.

Sounds good.  As long as we have a clear plan to remove it, so it doesn't just end up hanging around with a comment saying it should be removed.

**Review by pauladkisson — APPROVED** [review]
Tests are failing, but should pass after #1140 gets merged.

**Pull request merged**
