### PR TITLE
Synchronize timestamps

### PR DESCRIPTION
**Pull request by bendichter**
@CodyCBakerPhD here's a draft of the function to synchronize timestamps with pulses

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Function on my end has undergone updates since you made this branch, resulting in some conflicts.

A couple other things:

1) Can you demonstrate the intended input/output of this method with a series of tests against ground truths?
2) Can you point to a conversion where we've used this approach and how well it worked there?

**Comment by bendichter** [comment]
@CodyCBakerPhD I don't have an example of a conversion where I have used this, I was basing it on our conversations about what we needed. Do you think this might not be the right approach?

**Comment by CodyCBakerPhD** [comment]
> Do you think this might not be the right approach?

IDK if it's our place to determine if it's the 'right' approach or not for inferring such times given TTL info - as a statistical problem, there are infinitely many ways of going about it.

What differs in your approach from that of `synchronize_timestamps_between_systems` #237 seems to be the use of the intervals; it's hard for me to get a good grasp on what kind of input/output relation that would give when applied to some actual TTL signals, or how the estimated timing values would differ from the more basic interpolation, but that's something that could be well-communicated and explained via some thorough testing.

We can always offer multiple methods for timestamp inference given reference timings across systems, and accept/add new approaches in a modular way. Just need to think how that would look on the API level for interfaces using them to before sync (like an extra argument to `some_interface.synchronize_between_systems(...)` that specified the `method` they want to use.

**Comment by bendichter** [comment]
@CodyCBakerPhD I'm pretty sure they are equivalent, but just using `np.interp` as you have is a better solution.

**Pull request closed without merging**
