### PR TITLE
Return organized files from DANDI upload

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Requested by https://github.com/NeurodataWithoutBorders/nwb-guide/issues/658#issuecomment-1989243735

Give this a try and let me know

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Ah, right.

For GUIDE purposes I'd just strip everything before the second to last path. It should always have the pattern of a file `sub-.../sub-....ses-....nwb`

**Comment by CodyCBakerPhD** [comment]
Which is really what you're trying to display/communicate back the user I think

**Comment by garrettmflynn** [comment]
Hmm I brought this up because where these sessions originally came for is _not_ actually encoded anywhere in the leftover path. 

These were actually the outputs of two conversion pipelines using different data, which I'd selected as two folders in `~/NWB_GUIDE/conversions`

**Comment by CodyCBakerPhD** [comment]
> Hmm I brought this up because where these sessions originally came for is not actually encoded anywhere in the leftover path.

I don't understand what you mean - for reporting what was uploaded as a result of DANDI upload, do you not want to report the file paths as they will appear on the Dandiset? (not their original names chosen through the GUIDE, let alone the conversion output folder)

**Comment by CodyCBakerPhD** [comment]
> At least in standalone upload mode, I'd imagine that users would like to see a mapping between the discovered files and their DANDI equivalent, right?

I agree, but it's a different feature ('file organization preview') with its own challenges (direct mapping isn't returned by constituent functions; I know how to make it but would take little work)

> If not, then we should probably rename this on the GUIDE to New Files on DANDI.

Sure, that's a fine intermediate

**Comment by garrettmflynn** [comment]
Works on https://github.com/NeurodataWithoutBorders/nwb-guide/pull/665

**Review by garrettmflynn — APPROVED** [review]
Works on https://github.com/NeurodataWithoutBorders/nwb-guide/pull/665

**Pull request merged**
