### PR TITLE
Add stream control to Neuralynx

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
A fix desired for @TheChymera's data conversion - he has some multi-stream Neuralynx files and needs to be able to specify the stream to be written as the main vs. processed recording

Will need some tests to merge this, which will require investigating the GIN examples to see if any of those are multi-stream

### CODE REVIEW

**Comment by h-mayorquin** [comment]
The following are multi-stream:
```
/home/heberto/neuroconv_testing_data/ephy_testing_data/neuralynx/Cheetah_v5.6.3/original_data
NeuralynxRecordingExtractor: 2 channels - 2 segments - 2.0kHz - 1196.800s
/home/heberto/neuroconv_testing_data/ephy_testing_data/neuralynx/Cheetah_v5.7.4/original_data
NeuralynxRecordingExtractor: 5 channels - 4 segments - 32.0kHz - 43.595s
/home/heberto/neuroconv_testing_data/ephy_testing_data/neuralynx/Cheetah_v5.5.1/original_data
NeuralynxRecordingExtractor: 2 channels - 2 segments - 32.0kHz - 53.312s
/home/heberto/neuroconv_testing_data/ephy_testing_data/neuralynx/Cheetah_v6.3.2/incomplete_blocks
NeuralynxRecordingExtractor: 1 channels - 3 segments - 32.0kHz - 107.010s
/home/heberto/neuroconv_testing_data/ephy_testing_data/neuralynx/Cheetah_v5.4.0
/home/heberto/neuroconv_testing_data/ephy_testing_data/neuralynx/BML_unfilledsplit/original_data
NeuralynxRecordingExtractor: 1 channels - 2 segments - 29.4kHz - 0.045s
```

**Comment by CodyCBakerPhD** [comment]
@thechymera Did this change end up working for you?

**Comment by CodyCBakerPhD** [comment]
@TheChymera managed to find some testing data for it, finally added some tests for the capability

@h-mayorquin Could you give this a quick look when you get a chance? Just propagating stream control to SI

**Review by h-mayorquin — COMMENTED** [review]
Ok to me. I feel we should add a docstring describing the optional and what they mean. Stream is a very neo concept and I don't think is well know out there

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin OK copied docstring and helper class method from https://github.com/catalystneuro/neuroconv/blob/add_stream_control_neuralynx/src/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py#L55-L68

We can eventually talk about how to make a common interface to reduce the duplication there, but this is just a patch fix here

**Review by h-mayorquin — APPROVED** [review]
As you say, let's discuss how to handle streams outside of this as it is a necessary patch.

**Pull request merged**
